### ISSUE TITLE
Cannot import Raygun class into typescript - makes it difficult to create a typed member variable to keep a ref to teh instantiated object

### ISSUE THREAD

**Issue by chris-grabcad** [MindscapeHQ/raygun4node#100]
I'd like to write some code like this

```ts
import Raygun from "raygun";

class MyErrorReporter {
    private _raygun: Raygun;
    
    constructor() {
        this._raygun = new Raygun().init(...);
    }

    ...
}
```

but because the latest raygun.d.ts exports the following

```ts
declare class Raygun {
   ...
}
export declare const Client: typeof Raygun;
declare const _default: {
    Client: typeof Raygun;
};
export default _default;
```

I have to write this

```ts
import Raygun from "raygun";

class MyErrorReporter {
    private _raygun: any; // there seems to be no way to get Raygun.Client or Raygun to actually be recognised as a type
    
    constructor() {
        this._raygun = new Raygun.Client().init(...);
    }
    ...
}
```

This kind of makes typing pointless

... if the typescript exports were a bit simpler like this: -

```ts
declare namespace Raygun {
   export class Client { 
       ...
   }  
}
export = Raygun
```

it would be trivial

We're using typescript 3.8.3 as we cannot move to 3.9 just yet

**Comment by Widdershin** [comment]
Thanks for the report, I’ll make the types easier to consume in the next release.

**Comment by Widdershin** [comment]
As of v0.12.4 types can now be imported like this:

`import * as Raygun from 'raygun'`;

or

`import { Client } from 'raygun'`;

Unfortunately we don't support the default style of imports, as that would require a breaking change.

Thanks again for the report, sorry it took a little while to resolve.

**Comment by miquelbeltran** [comment]
Closing as this was resolved a while ago.
