### ISSUE TITLE
Using `raygunClient.send` with a string value results in error messages in Raygun

### ISSUE THREAD

**Issue by JasenPalmer** [MindscapeHQ/raygun4node#114]
When passing a string to the send method it results in the message being broken up into comma-separated characters that are prepended with the index of each character.

I have found that setting the `useHumanStringForObject` option to false is a way to get around this issue.

![image](https://user-images.githubusercontent.com/13548636/119598002-37e1fa00-be36-11eb-8cfd-53addbd0416d.png)

**Comment by Widdershin** [comment]
Thanks for the report @JasenPalmer, looking into this now.

**Comment by Widdershin** [comment]
Have prepared a fix that will be included in the next release, which should be over the next day or so.

Thanks again for the bug report, always appreciated.

**Comment by Widdershin** [comment]
We've released a fix for this issue as part of v0.13.1, which is now available on npm.
