### ISSUE TITLE
Node process does not exit when batch mode is used

### ISSUE THREAD

**Issue by pavelloz** [MindscapeHQ/raygun4node#122]
Hello,

Im migrating from sentry to raygun our CLI tool and it goes well up until the end.
Events arrive in GUI, nothing errors, but process is not exiting as it was before.

Im not sure if sentry was too eager to quit the process, but i decided to ask experts for help.

At the end of the day im replacing `Sentry.captureMessage(message);` with `raygunClient.send(message);` and this happens (currently) always when something has ended and process can be terminated (think `process.exit(x)`).

Now my question is: Should i manually exit process with error code that i determine, or there is some better way of dealing with it in raygun4node?

**Comment by pavelloz** [comment]
Ah, found it.

Just in case someone else has similar problem, this was the issue:
```
batch: true
```

Without batching process ends correctly.

**Comment by Widdershin** [comment]
@pavelloz nice work figuring this one out!

It's good that you were able to resolve this, but I'm going to reopen this issue as we should address this problem for batch mode, as batch mode has much better performance and shouldn't introduce any additional complexity.

Please let us know if you run into any other issues 🙂

**Comment by Widdershin** [comment]
Fixed as of the 0.13.2 release today, you should be able to use batch mode in scripts safely if desired :)
