### ISSUE TITLE
add support to catch unhandled promise

### ISSUE THREAD

**Issue by sfozz** [MindscapeHQ/raygun4node#137]
This seems to be a feature in raygun4js but is missing in this project.

**Comment by miquelbeltran** [comment]
I may be wrong, but I think this is going to be addressed when adding async support to `send()` in PR #181

**Comment by sfozz** [comment]
Have had a look at the PR, doesn't look to be providing anything like https://github.com/MindscapeHQ/raygun4js/blob/f2be885124abc234fd5adc839d4cffdc49a42f65/src/raygun.js#L456

Adding `async` support is a nice to have though :-)

**Comment by miquelbeltran** [comment]
I got it now, thanks for the link!
