### ISSUE TITLE
Not sending errors in async Lambda function

### ISSUE THREAD

**Issue by paul-uz** [MindscapeHQ/raygun4node#139]
I am following the code from the README, and on the blog post here, https://raygun.com/blog/error-reporting-aws-lambda/, although my function is async.

I can't stick `await` in front of the `.send()` method, as it shows an error saying "'await' has no effect on the type of this expression."

I am using `raygunClient.send(error)` in my `catch` blog, and triggering this code, but nothing comes through to the dashboard.

**Comment by paul-uz** [comment]
Turns out, you have to wrap it in an Promise, and await it.

eg

```TS
await new Promise<void>((resolve) => {
    raygunClient.send(error, {}, () => {
      resolve();
    });
});
```

**Comment by ProRedCat** [comment]
Thanks for pointing that out, we've added this to the Raygun4Node documentation now!

https://raygun.com/documentation/language-guides/nodejs/crash-reporting/installation/#aws-lambda

**Comment by paul-uz** [comment]
Well, you certainly did add something to the docs, sadly, it's a bit of a poor example.

It's snippets from the linked article, with no coherent explanation or solid example. Also, no example of async/await, just the poor example of using promise chaining.

The raygun node library is already massively out of date, how about we get some decent up to date documentation?

**Comment by ProRedCat** [comment]
Sorry to hear that it's not a great example @paul-uz, we'll definitely look into changing that up. If you have any recommendations on how it should be demonstrated please let me know :)

Additionally, we have got work for our Node provider planned now. You've mentioned that it's quite out of date so if you have any suggestions on what you'd like to see in a new version of the provider let me know and I'll put that in for what we can work on.

Thanks again for your suggestions, it's great to get community feedback on where we can do better.

**Comment by paul-uz** [comment]
Ideally I'm after something as simple as `await client.send(err);` (assuming a client is initialised)

No convoluted promise chains etc.
