### ISSUE TITLE
Getting "Error is too large to send to Raygun"

### ISSUE THREAD

**Issue by markcellus** [MindscapeHQ/raygun4node#140]
The package appears not to log errors with bigger strings. And the truncated chars aren't as helpful. Makes finding the cause of the error impossible. Is there any way to increase the maximum allowed bytes? Thanks for any info!

**Comment by markcellus** [comment]
Took a look at the code. Can the code at least `throw` an error [here](https://github.com/MindscapeHQ/raygun4node/blob/da8b8994a44283ef96644967f2300395f0226f00/lib/raygun.batch.ts#L78) instead of just `return`ing? So that we can log internal details about the error that causes it?

**Comment by miquelbeltran** [comment]
Hi. I am currently going through the package, fixing things, and implementing async/await support in general.
I think in this case it can be done, and it will properly warn the user when calling `send()`.

**Comment by markcellus** [comment]
Awesome! Making `send` return a Promise would be great. Thank you so much for working on this!
