### ISSUE TITLE
`.send()` does not with without async/await.

### ISSUE THREAD

**Issue by paul-uz** [MindscapeHQ/raygun4node#141]
Documentation leads you to believe that the `.send()` method can simply be called and data will be sent to your dashboard.

Using 0.13.2, this does not seem to be the case. I only get errors in my dashboard if I await the `.send()` method.

Are the docs out of date? Am I doing something wrong?

Here is my basic code, ran inside a Vitest test

```
    const foo = new Raygun.Client().init(
      {
        apiKey: '<MY_API_KEY>',
        reportColumnNumbers: true,
        reportUncaughtExceptions: true,
        batch: false,
        tags: ['vitest'],
      },
    );

    foo.send('test', {}, (res) => {
      console.log(res);
    });
```

**Comment by miquelbeltran** [comment]
Resolved in 0.15.0-0
