### ISSUE TITLE
Improve async behaviour when sending

### ISSUE THREAD

**Issue by TheRealAgentK** [MindscapeHQ/raygun4node#146]
>Ideally I'm after something as simple as `await client.send(err);` (assuming a client is initialised)
>No convoluted promise chains etc.

_Originally posted by @paul-uz in https://github.com/MindscapeHQ/raygun4node/issues/139#issuecomment-2071769894_
            
Note from Kai: see full thread in #139 for more context

**Comment by TheRealAgentK** [comment]
There's additional info and an already existing ticket from the OP in #141.

**Comment by miquelbeltran** [comment]
Resolved in 0.15.0-0
