### ISSUE TITLE
Memory Spikes when we use Raygun

### ISSUE THREAD

**Issue by donspaulding** [MindscapeHQ/raygun4node#20]
We have a node app that we wanted to put onto Raygun, but every time we hook it up, our nodejs processes chew up all available RAM and our servers start to swap.

Are there any known issues of this?  Is there any way we can pinpoint the issue further?

**Comment by dwnz** [comment]
Hey - are you able to email me (daniel@mindscape.co.nz) a few extra details eg Node version, OS, how quickly memory is used up, if you're using express/another framework. Have been running a basic Express app all morning, haven't noticed any major spikes.

Cheers!

**Comment by fundead** [comment]
Closing this one for now - if you still notice the issue please let us know your Node version/framework and environment details and we'll take a look.
