### ISSUE TITLE
Error: Cannot find module './raygun.sync.worker'

### ISSUE THREAD

**Issue by paul-uz** [MindscapeHQ/raygun4node#208]
I'm trying to test Raygun in RunJS, but after installing the package, and importing Raygun into my code, I get this error.

**Comment by miquelbeltran** [comment]
Hi @paul-uz is this with `0.15.0-0`? 

Do you have the same problem with an older version, e.g. installing `raygun@0.13.2`

**Comment by paul-uz** [comment]
> Hi @paul-uz is this with `0.15.0-0`? 
> 
> Do you have the same problem with an older version, e.g. installing `raygun@0.13.2`

Looks like it was an issue with runs and an ESM related setting.
