### ISSUE TITLE
enable_reporting configuration option

### ISSUE THREAD

**Issue by Radagaisus** [MindscapeHQ/raygun4node#21]
Would be nice to have an `enable_reporting` configuration option to the client, similar to how it's done in the Rails client.

**Comment by fundead** [comment]
Apologies for the delay in response to this ticket. That particular property happens to be specific to the Rails provider and is coupled to Rails' first class support for environments (e.g by default it is enabled in prod only). We've had more than a few complaints about people expecting one default over the other and surfacing something which can silence the provider has proven a pain point both during the initial setup and debugging the integration down the track. We're going to hold off on adding support for this during this release and as we haven't had many other requests for it, but if we receive more demand for it as a requirement we can add it in future.
