### ISSUE TITLE
Incorrect docs

### ISSUE THREAD

**Issue by aexmachina** [MindscapeHQ/raygun4node#22]
The [setup docs](https://raygun.io/docs/languages/node-js) suggest that the `.send()` method is synchronous because the example doesn't provide a callback, but in fact it's async (as it should be). If there's a slow connection then the example code will exit before the error is sent. Also, the exit code in the example code is wrong. This should be:

```js
d.on('error', function(err){
  setTimeout(function() {
    process.exit(1);
  }, 5000).unref();

  raygunClient.send(err, null, function() {
    process.exit(1); // use the correct exit code
  });
});
```

Also, I think that the interface for the RaygunClient#user method is unexpected. Here's my working implementation:

```js
    raygunClient.user = function (req) {
      return () => {
        if (req && req.auth) {
          return req.auth.serialize();
        }
      };
    };
```

I think that returning a function is unnecessary and I should be able to just return the object hash:

```js
    raygunClient.user = function (req) {
      if (req && req.auth) {
        return req.auth.serialize();
      }
    };
```

**Comment by aexmachina** [comment]
Oh, and another thing: I get a deprecation warning from the messageBuilder:

```
express deprecated req.host: Use req.hostname instead node_modules/raygun/lib/raygun.messageBuilder.js:114:26
```

**Comment by fundead** [comment]
Thanks for reporting this and apologies for the delay in response to this ticket. We have updated the documentation on the public site for the domains example. Regarding the user parameters, this accepts both a callback function (necessary for libraries such as Passport) and direct synchronous calling it as a setter (in the case the data is immediately available).

We're also now preferring `req.hostname` so this warning should no longer be present.
