### ISSUE TITLE
Is 0.15.0-0 a beta or stable build?

### ISSUE THREAD

**Issue by mcfarljw** [MindscapeHQ/raygun4node#223]
I'm only asking because typically when using the `-0` suffix it's mean to indicate some kind of pre-release version. In this case those this version has been released using the latest tag on NPM.

![Google Chrome 2024-05-16 at 09 56 54](https://github.com/MindscapeHQ/raygun4node/assets/4167341/37e143a0-c477-425a-b2d1-d71e509d7356)

**Comment by miquelbeltran** [comment]
Hi @mcfarljw it is indeed a pre-release to preview the async `send()` method. We plan on releasing a full `1.0.0` in the following days.

**Comment by mcfarljw** [comment]
@miquelbeltran thanks for clarifying! I recommend using release tags for pre-releases in the future otherwise anyone using `npm i raygun` might get an unintended build or something like `1.0.0-beta1` so `npm update` doesn't update it.

**Comment by miquelbeltran** [comment]
>  I recommend using release tags for pre-releases in the future otherwise anyone using npm i raygun might get an unintended build or something like 1.0.0-beta1

Sorry, I am not sure what you mean exactly by "using release tags for pre-releases", can you clarify?

A pre-release version does indeed that, when you run `npm install raygun`, it should currently download `0.14.0` which the last release.

Pre-releases are only downloaded when the user specifies the exact version, i.e. `npm install raygun@0.15.0-0`. It could have been named `0.15.0-alpha` but it should work the same.

**Comment by mcfarljw** [comment]
I don't think adding `-0` or any kind of suffix to the version marks it as a pre-release in the eyes of npm install. I just tried it on a new `package.json` file and by default it installed `raygun@0.15.0-0`.

![Warp 2024-05-17 at 07 56 21](https://github.com/MindscapeHQ/raygun4node/assets/4167341/8d58fd6c-e11d-4c69-bcfd-e7ee6b006ce5)

When checking npm it's using the `latest` tag which means it will be the default used when running the install command.

![Google Chrome 2024-05-17 at 07 58 19](https://github.com/MindscapeHQ/raygun4node/assets/4167341/8d6d2046-9197-40d0-903e-a966a3b4170a)

Vue (https://www.npmjs.com/package/vue?activeTab=versions) is a good example of using tags for alpha and beta builds that are not installed by default. In the screenshot below npm install would install version `3.4.27` but if you want the alpha or beta branches you'd need to do something like `npm i vue@alpha`. I also commonly see the tag next used like with React (https://www.npmjs.com/package/react?activeTab=versions).

![Google Chrome 2024-05-17 at 08 04 06](https://github.com/MindscapeHQ/raygun4node/assets/4167341/24f74384-13ed-42c7-b9c5-88de65c8c668)

For the raygun library you can set the version to `"version": "0.15.0-0` but if you want to make it an opt-in non-default install you'll need to do something like `npm publish --tag next` otherwise it'll get tagged as the latest version to be installed. Then users would need to run `npm i raygun@next` to get the pre-release build. Hope that helps!

**Comment by mcfarljw** [comment]
I'd also like to add that npm allows for adding tags after being published so if you wanted you could run `npm dist-tag add raygun@0.15.0-0 alpha`.

**Comment by miquelbeltran** [comment]
Ahh, got it now, thanks for the help!

The release is now properly tagged:

![image](https://github.com/MindscapeHQ/raygun4node/assets/2494376/bdfa07b1-d334-4a72-94a3-9a358d19e5f4)

I believe the issue is because the `latest` tag override the semantic versioning of `0.15.0-0` and so that's why users were downloading it.

We will keep this in mind for the next pre-releases.

**Comment by TheRealAgentK** [comment]
I think in the future we probably should also adopt the style of using the tag name in the version identifier for non-stable releases:

`0.15.0-alpha.1` for instance in this case.
