### ISSUE TITLE
Raygun not getting any error properties

### ISSUE THREAD

**Issue by FredKSchott** [MindscapeHQ/raygun4node#24]
When I send an error to raygun, I lose all properties and meta data for that error. It looks like you do this intentionally in `setErrorDetails()` [(L#63)](https://github.com/MindscapeHQ/raygun4node/blob/7f850eb68f28c1d353a250434dfa331b339dfa7b/lib/raygun.messageBuilder.js#L63), but lots of libraries will append additional, essential information as error properties. This is a serious issue for us because it renders many of our serious postgres conflicts and errors useless.

#### console.log(err);
```
{ [error: duplicate key value violates unique constraint "short_urls_pkey"]
  name: 'error',
  length: 198,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(THE_SAME_ID) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'nbtinsert.c',
  line: '406',
  routine: '_bt_check_unique' }
```

#### raygunClient.send(error, //...
From "Raw Data" (different error, but sent through the same formatter with the same properties): 
![screen shot 2015-04-17 at 12 16 18 pm](https://cloud.githubusercontent.com/assets/622227/7209240/9914011c-e4fb-11e4-94ff-9be182c9867d.png)

**Comment by fundead** [comment]
Hi Fred,

The provider constructs the payload in that way as the value of the 'error' key has a 1-1 mapping to the Raygun webapp's dashboard. To provider arbitrary data you can pass in an object as the second parameter to Raygun.send() (https://github.com/MindscapeHQ/raygun4node#sending-custom-data). This allows you to build a model of the properties you care about on the error object (potentially all of them).

**Comment by FredKSchott** [comment]
Ah gotcha. So you're saying the "Error Details" panel of raygun doesn't support any other properties than those?

Thanks for the quick response!

**Comment by fundead** [comment]
That's correct - the userCustomData value is the generic bucket for unstructured user data. That gets rendered under the Custom Data tab in the webapp if present (formatted nicely, with support for nested arrays/objects/linebreaks in strings etc).

**Comment by FredKSchott** [comment]
great, that's what our original workaround was. 

Still, it would be nice to automatically grab any error properties from the error itself instead of having to pass in the error twice. The fact that raygun only supports a few specific properties was unexpected to me.
