### ISSUE TITLE
No JSON.stringify protection when sending errors to raygun

### ISSUE THREAD

**Issue by FredKSchott** [MindscapeHQ/raygun4node#25]
in [raygun.transport](https://github.com/MindscapeHQ/raygun4node/blob/7f850eb68f28c1d353a250434dfa331b339dfa7b/lib/raygun.transport.js#L14) the module stringifies the payload before sending.
```js
var data = JSON.stringify(options.message);
```

If the consumer provides any custom data here that cannot serialize, a new error is thrown and then neither one is reported. That user would have no idea they were losing error logs (unless they were watching the raw logs).

**Comment by fundead** [comment]
Hi Fred,

Thanks for reporting this one, you're correct and we should be guarding and logging this state. I've got this on my list to implement and will appear in the next release.

Callum Gavin
Mindscape Limited

**Comment by FredKSchott** [comment]
Awesome, great to hear!
