### ISSUE TITLE
utf8 characters causing 400 response from raygun

### ISSUE THREAD

**Issue by mmoskal** [MindscapeHQ/raygun4node#27]
The send function in raygun.transport.js has the following:
```
  var data = JSON.stringify(options.message);
  ...
    headers: {
        'Content-Type': 'application/json',
        'Content-Length': data.length,
```
The `Content-Length` header should be length in bytes, not in characters. One way to fix it is to replace the first line above with:
```
var data = new Buffer(JSON.stringify(options.message), "utf8");
```

**Comment by fundead** [comment]
Hi,

Thanks heaps for this report, looks like an important one to tidy up. I'll get a fix pushed in the very near term for this.

Regards,

Callum Gavin
Mindscape Limited
