### ISSUE TITLE
User Info: Use and behaviour of `isAnonymous`

### ISSUE THREAD

**Issue by TheRealAgentK** [MindscapeHQ/raygun4node#273]
**Please describe your new feature request**
As part of the review discussion of #218 we recognised a need to look into how `isAnonymous` works (and should work).

This issue is to discuss and reason about it.

More TBA - just wanted to create the ticket for now.

**Comment by miquelbeltran** [comment]
As discussed internally, devs should be able to set the `isAnonymous` flag freely.

Will prepare a PR with the change.
