### ISSUE TITLE
Async function for affected user tracking 

### ISSUE THREAD

**Issue by alFReD-NSH** [MindscapeHQ/raygun4node#41]
Currently this is not possible out of the box easily.

**Comment by fundead** [comment]
Firstly apologies for the delay in response to this ticket. This should be possible as `raygun.user` can be set to a callback function which can return the available user data at the time of sending (and it accepts a `request` param allowing the desired fields to be accessed. For instance:

```
raygunClient.user = function (req) {
  if (req.user) {
    return {
      identifier: req.user.username,
      email: req.user.email,
      fullName: req.user.fullName,
      firstName: req.user.firstName
    };
  }
}
```

If you or anyone else is having trouble with this or has extra requirements please let us know in a new issue.

**Comment by alFReD-NSH** [comment]
Sorry, I think I wasn't clear. In my app there's no req.user, to get the user we have to make an asynchronous function call. I was thinking something like this:

```
raygunClient.user = function (req, cb) {
  req.accessToken.getUser(function(err, user) {
    if (err) { console.error(err); }
    else {
      cb({
        identifier: req.user.username,
        email: req.user.email,
        fullName: req.user.fullName,
        firstName: req.user.firstName
      });
    }
  });
}
```
