### ISSUE TITLE
express handler ignores the errors nor there's any way to log errors

### ISSUE THREAD

**Issue by alFReD-NSH** [MindscapeHQ/raygun4node#42]
By errors I mean when status code is 4xx or 5xx. There should be note in the documentation about it at least so there's no surprise.

**Comment by fundead** [comment]
You're correct, there should be a note in the docs for this behavior and I'm adding on for the latest release. This would semantically be correct as these are not `Errors`, just status codes, and the 500 would most likely indicate that some invalid state was passed in and potentially handled internally, resulting in no Error object available to be sent to Raygun.
