### ISSUE TITLE
expressHandler does not work

### ISSUE THREAD

**Issue by fiatjaf** [MindscapeHQ/raygun4node#47]
It doesn't send any errors.

I don't understand this Express error handling thing, how does Express now that some function I register with `.use` is an error handler? It could be a normal request handler, couldn't it?

**Comment by dwnz** [comment]
Hey,

Here's an Express sample - https://github.com/MindscapeHQ/raygun4node/tree/master/examples/express-sample

Note line 47 in app.js - the Raygun use line needs to be just before you start the server.


Cheers,
Daniel
