### ISSUE TITLE
Add a typescript definition

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4node#53]

**Comment by DannyBrown** [comment]
I'd like to +1 this. You can't use the `raygun4js` .d.ts for this lib :(

**Comment by mcfarljw** [comment]
https://www.npmjs.com/package/@types/raygun does exist and gets a fair amount of weekly downloads that seem to be growing. It'd still be best to have officially supported typings.

**Comment by TheRealAgentK** [comment]
Hey all, I know this is an ancient ticket. The current library supports TS, hence I'm closing this generic ticket for now.

If there's anything specifically missing, please create a new issue.
