### ISSUE TITLE
raygun useSSL in options hash not working

### ISSUE THREAD

**Issue by danielcondemarin** [MindscapeHQ/raygun4node#55]
Hi,

Looks like useSSL property always evaluates to truthy.

```Ln 25``` in ```raygun.js```:
```
_useSSL = options.useSSL || true;
```

No matter what value is passed on the options useSSL will always be truthy.

**Comment by fundead** [comment]
Thanks for reporting this one and sending through the PR, and also apologies for the delay in release. This is going out today in v0.9.0.
