### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by MarkHerhold** [MindscapeHQ/raygun4node#60]
I'm trying to evaluate error reporting SaaS offerings and it doesn't appear that this project gets much attention from Raygun.

**Comment by CmdrKeen** [comment]
Hi Mark,

Yes, it is. Node is one of the most popular supported platforms on Raygun. We do need to do some clean ups on older issues and PR's however.

Happy to discuss anything you think it is missing / needs updating however.
