### ISSUE TITLE
Update nock from version 8.2.2 to 9.6.1

### ISSUE THREAD

**Issue by arnaudhound** [MindscapeHQ/raygun4node#69]
there is a security issue reported on lodash version 4.9.0. 
Nock version 8.2.2 that is used by raygun is build on version 4.9.0.
To fix this issue an update to nock to version 9.6.1 is recommended. this version uses lodash 4.17.10.

**Comment by lalomartins** [comment]
Hi,

updating a dependency in order to fix a security vulnerability is meaningless if you don't release the update. The latest released version of the raygun package still has the vulnerability.

**Comment by UberMouse** [comment]
Sorry about that, I just released v0.10.1
