### ISSUE TITLE
nock should be marked as a dev dependency

### ISSUE THREAD

**Issue by thinkjson** [MindscapeHQ/raygun4node#72]
Adding raygun as a dependency pulls in nock, lodash, et all because nock is marked as a dependency instead of a dev dependency in this package. Please move this in the package.json

**Comment by Liath** [comment]
While it's not a to shuttle around, this adds something like 7mb useless bytes to my builds.

**Comment by Widdershin** [comment]
Hi @thinkjson and @Liath, as of `v0.10.2` nock is now correctly set as a dev dependency, so your package trees should hopefully shrink accordingly.

I'm going to close this issue as fixed, but please feel free to comment or reopen if you have any more problems with this issue :)
