### ISSUE TITLE
Error: is not a valid URL.

### ISSUE THREAD

**Issue by tomderudder** [MindscapeHQ/raygun4node#83]
Raygun failed then I try to send the error.

Code:
```
const raygun = require('raygun')

export default {
  install(Vue, { id = null }) {
    if (!id) {
      throw new Error('raygun id is missing')
    }

    Vue.prototype.$raygun = new raygun.Client().init({
      apiKey: id
    })
  }
}
```
```this.$raygun.send(new Error('error de test'), { mykey: 'beta' })```

Error:
```Raygun: error Window.fetch: https://api.raygun.io:443https://api.raygun.io:443/entries is not a valid URL. occurred while attempting to send error with message: [object Object```

**Comment by CmdrKeen** [comment]
Hi @tomderudder 

Can you let us know the version of Node you're using and any other packages?

A quick test locally and this works, however your error message reads like somehow you're getting a concatenated address (it repeats in the error message which seems odd). 

Thanks for the extra info in advance!

**Comment by miquelbeltran** [comment]
Hi @tomderudder I will proceed with closing the issue as no information was provided.

If this issue is still happening, please let us know and we will reopen the ticket.
