### ISSUE TITLE
Automatically capture uncaught exceptions and rejections

### ISSUE THREAD

**Issue by samuel-holt** [MindscapeHQ/raygun4node#99]
Currently, capturing and sending uncaught exceptions and rejections needs to be done manually. Having a helper function that attaches the event handlers would greatly improve the developer experience, and remove the need to use the deprecated Domain API.

### Scope

- Add a helper function to allow uncaught exceptions and rejections to be sent to Raygun automatically (e.g. `raygunClient.reportUncaughtExceptions()`)
  - Use the [uncaughtExceptionMonitor](https://nodejs.org/api/process.html#process_event_uncaughtexceptionmonitor) with a fallback for older versions of Node (Added in: v13.7.0, v12.17.0)
  - Add support for unhandled rejections
- The Domain API is deprecated, so we should remove/replace the [using-domains](https://github.com/MindscapeHQ/raygun4node/tree/master/examples/using-domains) sample app.

**Comment by Widdershin** [comment]
We'll close this on release.

**Comment by Widdershin** [comment]
Released as part of v0.13.0
